---
# vars file for create-cluster
default_url_weavenet: "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
default_url_cilium: "https://raw.githubusercontent.com/cilium/cilium/1.9.3/install/kubernetes/quick-install.yaml"
