apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app1
        image: colabdevops/app1go:latest
        ports:
        - containerPort: 8080


apiVersion: v1
kind: Service
metadata:
  name: service-app
  namespace: default
spec:
  selector:
    app: app
  ports:
  - name: web
    port: 80
    targetPort: 8080
