apiVersion: v1
kind: Service
metadata:
  name: service-app2
  namespace: default
spec:
  selector:
    run: app2
  ports:
  - name: web
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-app1
  namespace: default
spec:
  selector:
    run: app1
  ports:
  - name: web
    port: 80
    targetPort: 80