- name: Remove Disable swap
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: 'swap'

- name: Disable swap
  command: swapoff -a

- name: Creating conf containerD
  copy:
    dest: "/etc/modules-load.d/containerd.conf"
    content: |
      overlay
      br_netfilter

- name: Disable swap
  command: modprobe overlay

- name: Disable swap
  command: modprobe br_netfilter

- name: Creating conf kubernetes
  copy:
    dest: "/etc/sysctl.d/kubernetes.conf"
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      
- name: Load System
  command: sysctl --system >/dev/null 2>&1

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - containerd
    - ca-certificates
    - curl
    - gnupg-agent
    - gnupg
    - software-properties-common

- name: Load System
  command: sysctl --system >/dev/null 2>&1

- name: Create containerd directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory

- name: Load Sys containerd file
  command: containerd config default > /etc/containerd/config.toml
  notify: Restart Containerd

- name: mount eBPF
  command: mount bpffs /sys/fs/bpf -t bpf


- name: Adicionando as chaves do repo apt do k8s
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    

- name: Adicionando o repo do k8s
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list



- name: Instalando os pacotes kubeadm, kubelet e kubectl
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - kubelet=1.21.0-00
    - kubeadm=1.21.0-00
    - kubectl=1.21.0-00

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: kubelet.conf.j2
    dest: /etc/default/kubelet
    owner: vagrant
    group: admin
    mode: '0777'
  notify: Restart Kubelet
    

- name: Download Helm
  get_url:
    url: https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz
    dest: /tmp/helm-v3.5.2-linux-amd64.tar.gz
    mode: '0777'

- name: unzip helm
  ansible.builtin.unarchive:
    src: /tmp/helm-v3.5.2-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy helm to bin
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin
    owner: vagrant
    group: admin
    mode: '0777'
    remote_src: yes

-