- name: remove network default vagrant
  command: rm -rf /etc/ansible/50-cloud-init.yaml

- name: add network cluster
  ansible.builtin.template:
    src: 50-vagrant.yaml.j2
    dest: /etc/netplan/50-vagrant.yaml
    owner: vagrant
    group: admin
    mode: '0777'