---
# handlers file for install-k8s
- name: Restart Containerd
  systemd:
    daemon_reload: yes
    name: containerd
    state: restarted

- name: Restart Kubelet
  service:
    name: kubelet
    state: restarted

- name: Restart Docker and Daemon
  systemd:
    daemon_reload: yes
    state: restarted
    name: docker

- name: Enable and mount BPFFSS
  service:
    name: sys-fs-bpf.mount
    enabled: yes
    state: started

- name: reload systemd
  command: systemctl daemon-reload